FROM --platform=$BUILDPLATFORM alpine:latest as certs
RUN apk --update add ca-certificates

FROM --platform=$BUILDPLATFORM alpine:latest
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
RUN apk --update --no-cache add wget && rm -rf /var/cache/apk/*

workdir /skoot-with-log-2